dist: bionic
language: go
addons:
  apt:
    packages:
    - bsdtar
go:
- '1.13'
git:
  depth: 500
sudo: false
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
install:
- "./tools/build.sh"
script:
- curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
- unzip awscli-bundle.zip
- "./awscli-bundle/install -b ~/bin/aws"
- "./tools/test.sh"
- "./tools/build_rel_notes.sh"
- "./tools/publish.sh"
after_script:
- tools/notify.sh digitalrebar/provision-plugins
notifications:
  slack:
    secure: Imuptg78FWWZlGVb8LBuwn45CeMfnHgf+pXbftR8mSGFRsg08jw38MIRtw/MAET3RJsciwDXf22AkgM8WgZ+fcUbJI4MGn2IvnM40T/imc5deqlMn1QdE5HasWrrBwfyY7hDu8XBexit+2fmYLGGrHX2fsbvUJepT4xOV8MZbZWMYueoBuL2bxNRR+lhjqVsKMq+/8q4g7hsKxYOdStEOZQIM13qI8dbIIQK4cCPQGtdNMGlNSX0a/nEFZmxDKh3WILssZcRst7SW3QldYppJO21PcTmY/zCTLJ5b7izweLczDmV77ckv61X50B8iaarhwEMFYs9Icg8U69mAkbqeU5HsWy1d2VDPDG+QW32VMTU371pVEzsmBVzArSXvldULmRzYcA+9LoYb5P6LNbq2y7tdimETOElbkMyw53hnb4ZPiypLWlwusZibCxGsJMp41MgbxxaMKxUgrBsAY9nSBg/oj7ixditveXm5IjqBJXfFyxuxfvcxssT15AiqFI3z+Mpoarq233V7E/c0AwdYc/iJKPtW8DG2uSjb0EMIKopXjEi/tz8ykVQH1UbKww5PvGfzCw2mCNF+Bc925coTs8gwaU+XOnqQesggUheAmpaQhbdPGpNYecbLgtQ3kafEBllTrgLyTqISkXlDMZybItP1C8GrEEshGWSEzBAEGU=
env:
  global:
  - secure: p+bWYTP2bQH+GPFBLDkhc6Rsa6STDNWtLcfK+2tOD4XVAeT1NhZyraAYbnGmY4Vx7eNSaLJweZHZHD20jzdT/xeaDIoFglb8UXWsvby0oapAanH8ZdhoyyJQxD8LhRH5Uy/WDF5YmzfjN0tU8I//O5JiP7XIT/8X/Gus9rAzH3mqgMZnbyKw1BN5rD5Uwb0JdxPLyyJUp+PmizuaM3Q+WQGFVaMAJaCRrQetaSGtMvO7us+vhJexHm4Y0STQEeikI5q3A3pz/CsQ/7IL8/uGW4wa25x8OZbcv7+j8iDNuQGeI+HtbTuK9JOXcLRhe54bTfKcUYv0s4YAarM8aLwDh+4duhLckZtFHyGwRT4Vht1kkPOtOEt0YMRuQV2MQH9/XqI1ij/gnt0u7NfDMfjD8TB09RC9pkpkkhTp1+pG4uBJWOWh7qxqjtZx9m+ElC2yqXyyb/9wOTFkISi4yFh0ZKSJc7Jd9UGtWyzGSXCXa9Iuc/p6l4V9G0u0tfhm1B/thL01ZPcNmPcCmM3uMCku8LM1wzB18e2N3b3P212c0W2p1HtG4IsN4Rv9ZfnzpzBFcDFD2rWSECxJanz7eBMxHkZx7fp7qYmHwzbKuJALthmjzuoL0b27HazqS3n/SZml5xpQrsCEcnrZCt0wjXW5tz8yyzYpu7znyP0N3OHPRDY=
  - secure: MJ0IpE53ZDWSETb8/rVkpWkz0U13nhVDpJJC0GA211H1+oO0YLr46APheK3PXFTTExNNxJTKaZcW4iDRrSPjuLzbkoTytURzAxst7EyiUAugnLcAAyq9h6ItY3jhm8VmO3mdBZSfsYGPkA6GxgwF52Rdub0A/cuZHVTYYBiW6iJCoWTBnQnJiEMynqVUzUj55Ss4fxf3Mo2xsK09ce8y/+RxYFm7oHWnbQZL5WXH9g6QoNdPkdvwS2IrEv/nd4frrks/vis2ySLiUtr/GE23+hGdiEDifZllTsJmYM+opnKwpuP/RSo1jtRN/voZ3FIuh3E5LtO2H/gm+M4RngxxPeLIp+LAzmvDt/XKlOOuiqFTUSPV7u09MPEI3ZwQZmLnHqWaCQ1Sm7qIO4A83oJjkFiHMYWuTCbNh7IUVFCcsc4JbxTMXFNRoo4R+jG0AZpdFqJe3frUuOR8pDWCtpLPkt9FT+Gv0Ds9kID9YnQpIeQqGt6684Pyl+5QcdPfdG+L9mMvCgyGFQV3fNFZxQ9rYMVMP4nkCg8MXgKkVqEmgd2DxZaxVoITW0FgYLhHe04pjfVgwVq/Jl3Pxn5LKxFOi1pCIr0UHI9JeBSeowqqGybk401JcHRLrtY41ESXnVMybv8/RKnNX6CSyuY8xcsAXa3ujw5CxdVNFLr6M2uMp14=
  - secure: veecvPv9xMH1DMPdQmDTfL4siaQGkS1cJtzdnA6WU1qGIaIxzPS/q813eFh/drlFSY8vHQ/L0bxdOtFTwWvbqBnywS9OPNRTB0EV7F3zzAh8h528b6a7k9pQ3UX7Fk1wIzFcNK7YWVALsGolQUpfQ9QNByGQsIj0dtKAZoZlhBsjp6Y/Ieoh0p3R4af37Q3WR9Ma8TxTKp2wf2e8Nm+4p8JKV/mH0bdMq2rc+pjgFUnXk4jZHorWWt+D8KPkkf5gPYZn/V/LNJuijJ4YKUUMyYiFJuhCSHFh/yHg+gj0+0QaXCdnnv4FDv+hLMWJcxGusT0vc//xjP6kDRoPSJMDq/dXkk1qI+yJrMFQsQFaJDqG2SB3OvqUqOhdIQPY+j5frdDCW5JNtus6SxbVwU2KPYUbIHaLvDbFkXWAR5Cn5EEgccUa/hnvK+I37G5Xi5dbQkWchhAXmvVOjjKiEOBRmJxzVBSgmyFIb/xvVV4sdS497Y3UJg8ZyQ0AiGUBgg1safn1FPbgPbrCtfA9FqngwgzYCtj5O4hOcEGltiQnrNQh+U3fpd0PiUqYZvYjqCbBab5JWCJKT19WlL07mriepRRiufBb8WETfz4S9uF89Yhy2K5X/YFIn0KYH71Iv6ky0NKRjK04vvxIqRMWVZfmJmfhLzLgKZJxSzAsl+syaV8=
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: rebar-catalog
  region: us-west-2
  local-dir: rebar-catalog
  acl: public_read
  skip_cleanup: true
  on:
    repo: digitalrebar/provision-plugins
    branch: v4
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: rebar-catalog
  region: us-west-2
  local-dir: rebar-catalog
  acl: public_read
  skip_cleanup: true
  on:
    repo: digitalrebar/provision-plugins
    tags: true
