---
Name: "esxi-install-certificate"
Description: "Install an SSL certificate and restart services."
Documentation: |
  Install an SSL certificate and restart services.
Meta:
  icon: "cloud"
  color: "yellow"
  title: "Digital Rebar"
Templates:
  - Name: "esxi-install-certificate.sh"
    Contents: |
      #!/usr/bin/env sh

      {{ if eq (.Param "rs-debug-enable") true }}set -x{{ end }}

      set -e

      cd /etc/vmware/ssl

      # Save off files
      echo ">>> Backing up existing certificates to 'rui.key.back' and 'rui.crt.back'"
      cp rui.key rui.key.back
      cp rui.crt rui.crt.back

      RC=norestart

      {{ if and ( .ParamExists "esxi/ssl-key" ) ( .ParamExists "esxi/ssl-certificate" ) -}}

      RC=restart
      # Put new files in place
      echo ">>> Writing new 'rui.key' file"
      cat >rui.key <<EOF
      {{ .Param "esxi/ssl-key" -}}
      EOF

      echo ">>> Writing new 'rui.crt' file"
      cat >rui.crt <<EOF
      {{ .Param "esxi/ssl-certificate" -}}
      EOF

      {{ else -}}

      {{ if not ( .ParamExists "esxi/ssl-key" ) -}}
      echo "+++ No 'esxi/ssl-key' set"
      {{ end -}}

      {{ if not ( .ParamExists "esxi/ssl-certificate" ) -}}
      echo "+++ No 'esxi/ssl-certificate' set"
      {{ end -}}

      {{ if .Param "esxi/regenerate-certificates" }}
      RC=restart
      echo ">>> Regenerating self-signed certificates"
      /sbin/generate-certificates

      {{ end -}}

      {{ end -}}

      # Restart services
      if [[ $RC == restart ]]; then
      echo ">>> Restarting all services"
      /sbin/services.sh restart
      {{ template "esxi-service-verify.sh.tmpl" . }}
      fi

      exit 0
