---
Name: ble/config-override
Description: A template to override the BLE config.txt with.
Documentation: |
  Set this parameter to the name of a Template in the system, to
  override the Blancco Disk Eraser (BLE) config file.  The existing
  templatize version will be completely erased by this template.

Meta:
  color: blue
  icon: file alternate
  title: RackN Content
Secure: false
Schema:
  type: string
